;;(setq printer-name "bvm102")
(setq printer-name "bvc101")
(setq ps-print-header t)
(setq ps-print-header-frame nil)
(setq ps-show-n-of-n t)
(setq ps-spool-duplex t)
(setq ps-auto-font-detect t)
(setq ps-n-up-printing 2)
(setq ps-paper-type (quote a4))
(setq ps-font-size 12.0)
